services:
  web:
    build:
      dockerfile: GAPP.Dockerfile
    volumes:
      - gapp_data:/data 
    ports:
      - "4000:4000" 
  cdp:
    build:
      dockerfile: CDP.Dockerfile
    volumes:
      - cdp_data:/cdp 
    ports:
      - "5060:8000"
  ldp:
    build:
      dockerfile: LDP.Dockerfile
    configs:
      - source: ldp_config
        target: /config.json


configs:
  ldp_config:
    file: ./ldp_config.json

volumes:
  cdp_data:
    name: "cdp_data_volume"
  gapp_data:
    name: "gapp_data_volume"
